"""add_is_active_to_users

Revision ID: 769190d5664d
Revises: 8a3c9396fb08
Create Date: 2026-07-20 12:27:24.424777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '769190d5664d'
down_revision: Union[str, Sequence[str], None] = '8a3c9396fb08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    """op.alter_column('datasets', 'dataset_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('datasets', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('datasets', 'dataset_path',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('datasets', 'source_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('datasets', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('model_registry_run_id_fkey'), 'model_registry', type_='foreignkey')
    op.create_foreign_key(None, 'model_registry', 'pipeline_runs', ['run_id'], ['id'])
    op.drop_constraint(op.f('monitoring_deployment_id_fkey'), 'monitoring', type_='foreignkey')
    op.create_foreign_key(None, 'monitoring', 'deployments', ['deployment_id'], ['id'])
    op.alter_column('pipeline_logs', 'run_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('pipeline_logs', 'log_message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('trained_models', 'run_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('trained_models', 'model_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)"""
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    """op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))"""
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    """op.alter_column('users', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)"""
    op.drop_column('users', 'is_active')
    """op.alter_column('trained_models', 'model_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('trained_models', 'run_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('pipeline_logs', 'log_message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('pipeline_logs', 'run_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'monitoring', type_='foreignkey')
    op.create_foreign_key(op.f('monitoring_deployment_id_fkey'), 'monitoring', 'deployments', ['deployment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'model_registry', type_='foreignkey')
    op.create_foreign_key(op.f('model_registry_run_id_fkey'), 'model_registry', 'pipeline_runs', ['run_id'], ['id'], ondelete='CASCADE')
    op.alter_column('datasets', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('datasets', 'source_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('datasets', 'dataset_path',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('datasets', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('datasets', 'dataset_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)"""
    # ### end Alembic commands ###
